# Generated by Django 6.0.1 on 2026-02-02 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_datospersonales_experiencia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DatosPersonales',
        ),
        migrations.DeleteModel(
            name='Experiencia',
        ),
    ]
